model_params:
  in_channels: 1
  convbn_blocks: 3
  conv_kernel_size: [2,2,2]
  conv_kernel_strides: [2, 2, 2]
  convbn_channels: [1, 16, 32, 64]
  enc_fc_layers: [576, 128, 2]
  enc_fc_mu_activation:
  enc_fc_var_activation:
  conv_activation_fn: 'leaky'
  enc_fc_activation_fn: 'leaky'
  dec_fc_layers: [2, 128, 576]
  dec_fc_activation_fn: 'leaky'
  transpose_bn_blocks: 3
  transposebn_channels: [64, 32, 16, 1]
  transpose_kernel_size: [3,2,2]
  transpose_kernel_strides: [2,2,2]
  transpose_activation_fn: 'tanh'
  log_variance: True
  latent_dim: 2
  concat_channel: False
  decoder_fc_condition: False
  num_classes: 10
  conditional: False

# model_params:
  down_channels: [1, 16, 32, 64]
  down_kernel: [3, 3, 3]
  down_padding: [1, 1, 1]
  down_stride: [1, 1, 1]
  enc_fc_channels: [576, 128, 2]
  up_kernel: [3, 2, 2]
  up_padding: [0, 0, 0]
  up_stride: [2, 2, 2]


train_params:
  task_name: 'vae_new'
  batch_size: 64
  epochs: 10
  kl_weight: 0.00001
  lr: 0.005
  crit: 'l2'
  ckpt_name: 'best_vae_kl_ckpt.pth'
  seed: 111
  save_training_image: True

  train_path: 'data/mnist/train/images'
  test_path: 'data/mnist/test/images'
  output_train_dir: 'output'
  save_latent_plot: True